test
Signed-off-by: Poorna Gottimukkula <Poorna.Gottimukkula1@ibm.com>

diff --git a/jobs/pipelines/powervs/ipi/4.15/daily-ipi4.15-powervs-madrid04/Jenkinsfile b/jobs/pipelines/powervs/ipi/4.15/daily-ipi4.15-powervs-madrid04/Jenkinsfile
--- a/jobs/pipelines/powervs/ipi/4.15/daily-ipi4.15-powervs-madrid04/Jenkinsfile
+++ b/jobs/pipelines/powervs/ipi/4.15/daily-ipi4.15-powervs-madrid04/Jenkinsfile
@@ -2,9 +2,9 @@
 
 pipeline {
     agent {
-        kubernetes {
-            inheritFrom 'jenkins-agent'
-        }
+        node {
+            label 'ipi-agent'
+        } 
     }
     environment {
         //users and credentials. All must be defined in Jenkins Credentials
@@ -40,7 +40,7 @@ pipeline {
         OCP_RELEASE = "4.15"
         CLUSTER_NAME="rdr-cicd-mad04-415"
         CLUSTER_DIR="./ipi-install"
-        OPENSHIFT_CLIENT_TARBALL_AMD64="https://mirror.openshift.com/pub/openshift-v4/amd64/clients/ocp/4.15.0-rc.8/openshift-client-linux.tar.gz"
+        OPENSHIFT_CLIENT_TARBALL_AMD64="https://mirror.openshift.com/pub/openshift-v4/ppc64le/clients/ocp/4.15.0-rc.8/openshift-client-linux.tar.gz"
         //OPENSHIFT_INSTALLER_URL="https://mirror.openshift.com/pub/openshift-v4/amd64/clients/ocp/4.15.0-rc.8/openshift-install-linux.tar.gz"
         POWERVS = true
 	 }
@@ -77,16 +77,17 @@ pipeline {
                         }
                             sh '''
                                 cd ${WORKSPACE}/deploy
+                                rm -rf ~/.kube
                                 echo ${PULL_SECRET} > ~/.pullSecret
                                 cp -rf ${WORKSPACE}/deploy/id_rsa.pub ~/.ssh/id_installer_rsa.pub
-                                git clone https://github.com/Poorna-Gottimukkula1/powervs-hack.git
+                                git clone https://github.com/Poorna-Gottimukkula1/powervs-hack.git -b ipi
                                 oc adm release extract --tools ${OPENSHIFT_INSTALL_RELEASE_IMAGE_OVERRIDE} --to openshift-tools -a ~/.pullSecret
-                                tar -xvf ./openshift-tools/openshift-install-linux-amd64-${OPENSHIFT_INSTALL_RELEASE_VERSION}.tar.gz  -C /usr/local/bin
-                                tar -xvf ./openshift-tools/openshift-client-linux-amd64-${OPENSHIFT_INSTALL_RELEASE_VERSION}.tar.gz  -C /usr/bin
+                                tar -xvf ./openshift-tools/openshift-install-linux-${OPENSHIFT_INSTALL_RELEASE_VERSION}.tar.gz  -C /usr/local/bin
+                                tar -xvf ./openshift-tools/openshift-client-linux-${OPENSHIFT_INSTALL_RELEASE_VERSION}.tar.gz  -C /usr/local/sbin
                                 rm -rf ./openshift-tools
                                 #curl -L "${OPENSHIFT_INSTALLER_URL}" > openshift-install-linux.tar.gz
                                 #tar -xvf openshift-install-linux.tar.gz  -C /usr/local/bin
-                                 # setup oc client
+                                # setup oc client
                                 #if [ ${OPENSHIFT_CLIENT_TARBALL_AMD64} ]; then
                                 #    wget --quiet "${OPENSHIFT_CLIENT_TARBALL_AMD64}" -O - | tar -xz
                                 #    [ $? -ne 0 ] && echo "unable to get oc tarball" && exit 1
@@ -160,7 +161,59 @@ pipeline {
                                 echo "Cluster operators are in degraded state after 90 mins Tearing off cluster!!"
                                 exit 1
                             fi
-                            '''
+                        '''
+                    }
+                    catch (err) {
+                        echo 'Error ! All Cluster Operators are not Up  !'
+                        env.FAILED_STAGE=env.STAGE_NAME
+                        throw err
+                    }
+                }
+
+            }
+        }
+        stage('Run openshift-tests-private Suite') {
+            when { expression { return env.DEPLOYMENT_STATUS == "true"; } }
+            steps {
+                 script {
+                    ansiColor('xterm') {
+                        echo ""
+                    }
+                    try {
+                        sh '''#!/bin/bash -x
+                        cd ${WORKSPACE}/deploy
+                        export PATH=$PATH:/usr/local/go/bin/
+                        export PATH=$PATH:/root/operator-sdk/build
+                        export PATH=$PATH:/root/operator-framework-olm-0e8b957251ce3edb82ca8d9139380b18df1fe55c/bin
+                        git clone git@github.com:openshift/openshift-tests-private.git
+                        cd openshift-tests-private
+                        make build
+                        cp -rp ./bin/extended-platform-tests /usr/local/bin/
+                        cd ${WORKSPACE}/deploy
+                        chmod 777 ${WORKSPACE}/scripts/openshift-tests-private.sh && ${WORKSPACE}/scripts/openshift-tests-private.sh | tee ./openshift-private-tests.log 2>&1
+                        '''
+                    }
+                    catch (err) {
+                        echo 'Error ! All Cluster Operators are not Up  !'
+                        env.FAILED_STAGE=env.STAGE_NAME
+                        throw err
+                    }
+                }
+
+            }
+        }
+        stage('Run verification/cucushift tests') {
+            when { expression { return env.DEPLOYMENT_STATUS == "true"; } }
+            steps {
+                 script {
+                    ansiColor('xterm') {
+                        echo ""
+                    }
+                    try {
+                        sh '''#!/bin/bash
+                        cd ${WORKSPACE}/deploy
+                        chmod 777 ${WORKSPACE}/scripts/verification-ipi.sh && ${WORKSPACE}/scripts/verification-ipi.sh | tee ./verification.log 2>&1
+                        '''
                     }
                     catch (err) {
                         echo 'Error ! All Cluster Operators are not Up  !'
@@ -174,40 +227,39 @@ pipeline {
     }
     post {
         always {
-            archiveAllArtifacts("deploy/metadata.json")
-            script {
-               sh '''#!/bin/bash
-                echo "Cleanup IPI cluster"
-                if [ -d ${WORKSPACE}/deploy ];then
-                    cd ${WORKSPACE}/deploy
-                else
-                  exit 1
-                fi
-                ibmcloud login -a cloud.ibm.com -r ${VPCREGION} -g ${RESOURCE_GROUP} -q --apikey=${IBMCLOUD_API_KEY}
-                for I in infrastructure-service cloud-internet-services dl-cli dns; do
-                   ibmcloud plugin install ${I}
-                done
-                ./powervs-hack/scripts/dump-powervs.sh
-                retries=0
-                until [ "$retries" -ge 3 ]
-                do
-                  cp -f ${CLUSTER_DIR}/metadata.json ./metadata_copy.json
-                  openshift-install destroy cluster  --log-level=debug --dir ${CLUSTER_DIR} || true
-                  mv -f ./metadata_copy.json ${CLUSTER_DIR}/metadata.json
-                  retries=$((retries+1))
-                done
-                #Get connections
-                ibmcloud login -a cloud.ibm.com -r ${VPCREGION} -g ${RESOURCE_GROUP} -q --apikey=${IBMCLOUD_API_KEY}
-                cons=$(ibmcloud pi cons| grep "cloud-con-rdr-cicd"|awk '{print $1}')
-                echo "$cons"| while IFS= read -r line ; do ibmcloud pi connection-delete $line; done || true
-                #Get DHCP
-                ./powervs-hack/scripts/get-dhcp.sh || true
-                dhcp_id=$(./powervs-hack/scripts/get-dhcp.sh | awk 'FNR == 4 {print $1}')
-                ./powervs-hack/scripts/get-dhcp.sh $dhcp_id -d || ibmcloud pi ind $dhcp_id || true
-                '''
-            }
-            notifyBySlack(currentBuild.result, env.MESSAGE)
-            cleanWs()
+            archiveAllArtifacts("deploy/metadata.json", "deploy/verification.log", "deploy/openshift-private-tests.log", "deploy/extended-platform-tests_cmd.log")
+            // script {
+            //    sh '''#!/bin/bash
+            //     echo "Cleanup IPI cluster"
+            //     if [ -d ${WORKSPACE}/deploy ];then
+            //         cd ${WORKSPACE}/deploy
+            //     else
+            //       exit 1
+            //     fi
+            //     ibmcloud login -a cloud.ibm.com -r ${VPCREGION} -g ${RESOURCE_GROUP} -q --apikey=${IBMCLOUD_API_KEY}
+            //     for I in infrastructure-service cloud-internet-services dl-cli dns; do
+            //        ibmcloud plugin install ${I}
+            //     done
+            //     ./powervs-hack/scripts/dump-powervs.sh
+            //     retries=0
+            //     until [ "$retries" -ge 3 ]
+            //     do
+            //       cp -f ${CLUSTER_DIR}/metadata.json ./metadata_copy.json
+            //       openshift-install destroy cluster  --log-level=debug --dir ${CLUSTER_DIR} || true
+            //       mv -f ./metadata_copy.json ${CLUSTER_DIR}/metadata.json
+            //       retries=$((retries+1))
+            //     done
+            //     #Get connections
+            //     ibmcloud login -a cloud.ibm.com -r ${VPCREGION} -g ${RESOURCE_GROUP} -q --apikey=${IBMCLOUD_API_KEY}
+            //     cons=$(ibmcloud pi cloud-connection ls| grep "cloud-con-rdr-cicd"|awk '{print $1}')
+            //     echo "$cons"| while IFS= read -r line ; do ibmcloud pi cloud-connection delete $line; done || true
+            //     #Get DHCP
+            //     ./powervs-hack/scripts/get-dhcp.sh || true
+            //     dhcp_id=$(./powervs-hack/scripts/get-dhcp.sh | awk 'FNR == 4 {print $1}')
+            //     ./powervs-hack/scripts/get-dhcp.sh $dhcp_id -d || ibmcloud pi ins delete $dhcp_id || true
+            //     '''
+            // }
+            //cleanWs()
         }
     }
 }
