Change image repo quay for multi arch images
Signed-off-by: Poorna Gottimukkula <Poorna.Gottimukkula1@ibm.com>

diff --git a/jobs/pipelines/mirror-openshift-release/Jenkinsfile b/jobs/pipelines/mirror-openshift-release/Jenkinsfile
--- a/jobs/pipelines/mirror-openshift-release/Jenkinsfile
+++ b/jobs/pipelines/mirror-openshift-release/Jenkinsfile
@@ -29,9 +29,9 @@ pipeline {
                     sh '''
                         cd ${WORKSPACE}/scripts
                         nerdctl login -u ${ARTIFACTORY_USER} -p ${ARTIFACTORY_TOKEN} ${DOCKER_REGISTRY}
-                        oc login --token=${CI_OCP_TOKEN} --server=https://api.ci.l2s4.p1.openshiftapps.com:6443
-                        oc registry login --skip-check --registry-config ~/.docker/config.json
-                        ./mirror-images.sh || true
+                        #oc login --token=${CI_OCP_TOKEN} --server=https://api.ci.l2s4.p1.openshiftapps.com:6443
+                        #oc registry login --skip-check --registry-config ~/.docker/config.json
+                        #./mirror-images.sh || true
                     '''
                     }
                     catch (err)
@@ -52,9 +52,20 @@ pipeline {
                     try
                     {
                     sh '''
-                    curl https://openshift-release-ppc64le.apps.ci.l2s4.p1.openshiftapps.com/ > builds.raw.txt
-                    cat builds.raw.txt | grep -A 2 '<td class="text-monospace"' | grep -v '^--' | awk 'NR%3{printf "%s ",$0;next;}1'|grep -v 'Failed' |sed 's|\\([^/]*/\\)\\{4\\}[^>]*>\\([^>]*\\).*title[^"]*"\\([^"]*\\).*|\\2  \\3|' | sed 's/<\\/a//'| sort -k2 -r |awk -v registry="${DOCKER_REGISTRY}" '{print registry"/ocp-ppc64le/release-ppc64le:"$0}' > all-builds.txt
-                    #All Builds
+                    curl https://openshift-release-multi.apps.ci.l2s4.p1.openshiftapps.com/ > builds.raw.txt
+                    cat builds.raw.txt | grep -A 2 '<td class="text-monospace"' | grep -v '^--' | awk 'NR%3{printf "%s ",$0;next;}1'|grep -v 'Failed' |sed 's|\\([^/]*/\\)\\{4\\}[^>]*>\\([^>]*\\).*title[^"]*"\\([^"]*\\).*|\\2  \\3|' | sed 's/<\\/a//'| sort -k2 -r > raw-all-builds.txt
+
+                    for build in $(cat raw-all-builds.txt|awk '{print $1}'); do
+                      if echo $build | grep -q "nightly"; then
+                        echo quay.io/openshift-release-dev/ocp-release-nightly:${build} >> all-builds.txt
+                      else
+                        if echo $build | grep -q "multi"; then
+                            echo quay.io/openshift-release-dev/ocp-release:${build} >> all-builds.txt
+                        else
+                            echo quay.io/openshift-release-dev/ocp-release:${build}-multi >> all-builds.txt
+                        fi
+                      fi
+                    done
                     grep '4\\.11\\.[0-9]\\?[0-9]' all-builds.txt  > all-4.11-builds.txt
                     grep '4\\.12\\.[0-9]\\?[0-9]' all-builds.txt  > all-4.12-builds.txt
                     grep '4\\.13\\.[0-9]\\?[0-9]' all-builds.txt  > all-4.13-builds.txt
